// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="A Passion for Tradition"
          descriptions={[
            "Ocho Rios Jamaican Cuisine was founded with a simple goal: to share the vibrant, authentic flavors of Jamaica with the Roanoke community. Every recipe is rooted in tradition, passed down through generations.",
            "We take pride in our spotless, relaxing environment and our commitment to friendly, personable service. Whether you're a long-time lover of jerk chicken or trying curry goat for the first time, we invite you to experience a true island meal.",
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
