// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "comparison" section.

import React from 'react';
import FeaturesComparison from '@/components/sections/features/FeaturesComparison';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ComparisonSection(): React.JSX.Element {
  return (
    <div id="comparison" data-section="comparison">
        <SectionErrorBoundary name="comparison">
              <FeaturesComparison
          tag="Why Choose Us?"
          title="The Authentic Difference"
          description="What sets Ocho Rios apart in the Roanoke culinary scene."
          negativeItems={[
            "No pre-packaged or mass-produced meals",
            "No shortcut shortcuts in traditional prep",
            "Not just another generic restaurant",
            "No compromise on quality standards",
          ]}
          positiveItems={[
            "Authentic Jamaican spices and seasonings",
            "Generous, satisfying portion sizes",
            "Spotless and welcoming atmosphere",
            "Fast and professional service",
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
