// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Visit Us Today"
          text="Ready for an authentic island meal? Join us at 2102 Williamson Rd NE, Roanoke, VA."
          primaryButton={{
            text: "Call Now",
            href: "tel:5409885560",
          }}
          secondaryButton={{
            text: "Get Directions",
            href: "https://maps.google.com/?q=2102+Williamson+Rd+NE+Roanoke+VA",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
