// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="Got Questions?"
          title="Frequently Asked Questions"
          description="Learn more about our services and operating hours."
          items={[
            {
              question: "Do you offer delivery?",
              answer: "Yes, we partner with Uber Eats for fast delivery to your door.",
            },
            {
              question: "What are your operating hours?",
              answer: "We are typically open from 12:30 PM. Please check our Google profile for real-time updates.",
            },
            {
              question: "Do you offer takeout?",
              answer: "Absolutely! You can call us to place an order for pickup.",
            },
            {
              question: "Do you offer catering?",
              answer: "We do accommodate catering requests. Please give us a call to discuss your event.",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
