/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";

const items = [
  {
    title: "Jerk Chicken",
    description: "Succulent, spice-rubbed chicken grilled to perfection.",
    imageSrc: "http://img.b2bpic.net/free-photo/baked-pumpkin-with-chicken-paprika_2829-13657.jpg"
  },
  {
    title: "Oxtails",
    description: "Tender oxtail slow-cooked in a rich, flavorful gravy.",
    imageSrc: "http://img.b2bpic.net/free-photo/top-view-delicious-goulash-olive-oil_23-2149388119.jpg"
  },
  {
    title: "Curry Goat",
    description: "A Jamaican staple cooked with aromatic spices.",
    imageSrc: "http://img.b2bpic.net/free-photo/delicious-goulash-ready-dinner_23-2149370900.jpg"
  },
  {
    title: "Brown Stew Chicken",
    description: "Classic Jamaican comfort in a savory dark stew.",
    imageSrc: "http://img.b2bpic.net/free-photo/cod-with-potatoes_123827-37163.jpg"
  },
  {
    title: "Fried Plantains",
    description: "Sweet, golden-fried slices of heaven.",
    imageSrc: "http://img.b2bpic.net/free-photo/still-life-recipe-with-plantain_23-2151062818.jpg"
  },
  {
    title: "Beef Patties",
    description: "Flaky crust filled with perfectly seasoned beef.",
    imageSrc: "http://img.b2bpic.net/free-photo/side-view-heap-chocolate-chip-cookies-with-cereals-nuts-cocoa-wooden_141793-6227.jpg"
  },
  {
    title: "Rice and Peas",
    description: "Our signature side dish, essential for every meal.",
    imageSrc: "http://img.b2bpic.net/free-photo/black-rice-plate-with-pumpkin-peas-carrots-baby-corn_1150-20973.jpg"
  }
];

type FeatureItem = {
  title: string;
  description: string;
  href?: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesImageBentoProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: [FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const MenuInline = () => {
  const gridClasses = [
    "md:col-span-2",
    "md:col-span-4",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-2",
    "md:col-span-2",
    "md:col-span-2",
  ];

  const staggerDelays = [
    0,
    0.1,
    0,
    0.1,
    0,
    0.1,
    0.2,
  ];

  return (
    <section aria-label="Features image bento section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Our Favorites"}</p>
          </div>

          <TextAnimation
            text={"Flavor-Packed Jamaican Classics"}
            variant={"fade-blur"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Explore our most loved dishes, prepared fresh daily."}
            variant={"fade-blur"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div className="w-content-width mx-auto grid grid-cols-1 md:grid-cols-6 gap-3">
          {items.map((item, index) => {
            const content = (
              <div className="relative h-80 xl:h-100 2xl:h-120 overflow-hidden">
                <ImageOrVideo
                  imageSrc={item.imageSrc}
                  videoSrc={item.videoSrc}
                  className="rounded group-hover:scale-105 transition-transform duration-500"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent pointer-events-none rounded" />

                <div className="absolute inset-x-5 bottom-5 xl:inset-x-6 xl:bottom-6 2xl:inset-x-7 2xl:bottom-7 flex flex-col text-white drop-shadow-md">
                  <span className="text-2xl font-semibold leading-snug truncate">{item.title}</span>
                  <span className="text-base leading-snug truncate">{item.description}</span>
                </div>
              </div>
            );

            return (
              <ScrollReveal key={index} variant="fade" delay={staggerDelays[index]} className={cls("col-span-1 group", gridClasses[index])}>
                {item.href ? (
                  <a href={item.href} className="block overflow-hidden rounded">
                    {content}
                  </a>
                ) : (
                  <div className="overflow-hidden rounded">
                    {content}
                  </div>
                )}
              </ScrollReveal>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default function MenuSection() {
  return (
    <div data-webild-section="menu" data-section="menu" id="menu">
      <MenuInline />
    </div>
  );
}
