// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "menu" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MenuSection(): React.JSX.Element {
  return (
    <div id="menu" data-section="menu">
        <SectionErrorBoundary name="menu">
              <FeaturesImageBento
          tag="Our Favorites"
          title="Flavor-Packed Jamaican Classics"
          description="Explore our most loved dishes, prepared fresh daily."
          items={[
            {
              title: "Jerk Chicken",
              description: "Succulent, spice-rubbed chicken grilled to perfection.",
              imageSrc: "http://img.b2bpic.net/free-photo/baked-pumpkin-with-chicken-paprika_2829-13657.jpg",
            },
            {
              title: "Oxtails",
              description: "Tender oxtail slow-cooked in a rich, flavorful gravy.",
              imageSrc: "http://img.b2bpic.net/free-photo/top-view-delicious-goulash-olive-oil_23-2149388119.jpg",
            },
            {
              title: "Curry Goat",
              description: "A Jamaican staple cooked with aromatic spices.",
              imageSrc: "http://img.b2bpic.net/free-photo/delicious-goulash-ready-dinner_23-2149370900.jpg",
            },
            {
              title: "Brown Stew Chicken",
              description: "Classic Jamaican comfort in a savory dark stew.",
              imageSrc: "http://img.b2bpic.net/free-photo/cod-with-potatoes_123827-37163.jpg",
            },
            {
              title: "Fried Plantains",
              description: "Sweet, golden-fried slices of heaven.",
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-recipe-with-plantain_23-2151062818.jpg",
            },
            {
              title: "Beef Patties",
              description: "Flaky crust filled with perfectly seasoned beef.",
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-heap-chocolate-chip-cookies-with-cereals-nuts-cocoa-wooden_141793-6227.jpg",
            },
            {
              title: "Rice and Peas",
              description: "Our signature side dish, essential for every meal.",
              imageSrc: "http://img.b2bpic.net/free-photo/black-rice-plate-with-pumpkin-peas-carrots-baby-corn_1150-20973.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
