// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsMediaCards
          tag="Our Growth"
          title="Serving Smiles Daily"
          description="We are proud to serve our vibrant community."
          metrics={[
            {
              value: "4.8",
              title: "Google Rating",
              description: "Based on 194 reviews and happy customers.",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-woman-bringing-food-table-having-fun-with-her-friends-lunch-time-home_637285-3146.jpg",
            },
            {
              value: "15+",
              title: "Authentic Recipes",
              description: "Time-honored family recipes crafted daily.",
              imageSrc: "http://img.b2bpic.net/free-photo/high-angle-chef-cooking_23-2148471935.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
