// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Voices of Our Guests"
          title="Trusted by Locals"
          description="Hear what our wonderful guests have to say about their experience."
          testimonials={[
            {
              name: "Black Star Dust",
              role: "Local Guide",
              quote: "Hands down, the absolute best Jamaican spot between DC and Atlanta! The flavors are incredibly savory and perfectly balanced.",
              imageSrc: "http://img.b2bpic.net/free-photo/older-friends-eating-restaurant_23-2149316782.jpg",
            },
            {
              name: "Nita Bur",
              role: "Local Guide",
              quote: "The oxtails are delicious! The rice and peas and curry goat are yummy. I'm glad we were able to order beef patties.",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-smiling-watching-man-playing-guitar-party_23-2149187061.jpg",
            },
            {
              name: "Don Marlowe",
              role: "Local Guide",
              quote: "Extraordinary customer service. Reasonable prices. Highly recommend this restaurant.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-smiley-woman-with-notebook_23-2148877764.jpg",
            },
            {
              name: "Sarah J.",
              role: "Guest",
              quote: "Everything I have tried here is authentic and cooked to perfection. The staff is so friendly!",
              imageSrc: "http://img.b2bpic.net/free-photo/friends-having-fun-while-traveling_52683-88086.jpg",
            },
            {
              name: "Michael K.",
              role: "Guest",
              quote: "The portions are generous and the flavors are just like home. My favorite spot in Roanoke.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-meat-with-baked-potatoes-eggplant-tomato-pepper-decorated-with-pomegranate-plate-served-table_176474-2442.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
